HOSTS:
  centos7:
    roles:
      - server
      - default
      - master
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: vagrant
  centos6:
    roles:
      - el6
    platform:   el-6-x86_64
    box:        centos/6
    hypervisor: vagrant

CONFIG:
  log_level: verbose
  type:      aio
  synced_folder: disabled
  vagrant_memsize: 256
# vb_gui: true
